name: json_matcher
version: 0.2.2
author: Alexey Karapetov <karapetov@gmail.com>
homepage: https://github.com/f3ath/json-matcher
description: "JSON Matchers for unit tests: encodesToJson() checks if the value encodes to expected JSON, isJson() checks if the string is expected JSON."
environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'
dependencies:
  convert: ">=2.0.0 <3.0.0"
  matcher: ">=0.12.3 <0.12.4"
dev_dependencies:
  test: ">=1.3.0 <1.4.0"
